import os

RUN_ENVIRONMENT = os.getenv("PRECRASH_ENV", "DEVELOPMENT")

SERVER_CORE_PORT = 5000
RISK_THRESHOLD_HIGH = 0.75
SPATIAL_SCAN_RADIUS_KM = 5.0
GEOGRAPHIC_FUZZ_RADIUS_METERS = 350
DEAD_MAN_HEARTBEAT_TIMEOUT_SEC = 300
BREADCRUMB_BUFFER_MAX_RECORDS = 50
EVENT_CRITICAL_INCIDENT = "incident_sos_trigger"
EARTH_RADIUS_EQUATORIAL_KM = 6371.0088